package dk.exchange;

import dk.crypto.CurrencyPair;

import java.util.Set;

public class CurrencyPairs {


    public final static Set<CurrencyPair> CURRENCY_PAIRS = Set.of(
            CurrencyPair.of("KAVA","ETH"),
            CurrencyPair.of("KAVA","EUR"),
            CurrencyPair.of("KAVA","USD"),
            CurrencyPair.of("DASH","EUR"),
            CurrencyPair.of("DASH","USD"),
            CurrencyPair.of("ICX","ETH"),
            CurrencyPair.of("ICX","EUR"),
            CurrencyPair.of("ICX","USD"),
            CurrencyPair.of("ETH","CAD"),
            CurrencyPair.of("ETH","JPY"),
            CurrencyPair.of("ETH","GBP"),
            CurrencyPair.of("ETH","CHF"),
            CurrencyPair.of("ETH","EUR"),
            CurrencyPair.of("ETH","USD"),
            CurrencyPair.of("ETH","AUD"),
            CurrencyPair.of("ADA","ETH"),
            CurrencyPair.of("ADA","EUR"),
            CurrencyPair.of("ADA","USD"),
            CurrencyPair.of("BAT","ETH"),
            CurrencyPair.of("BAT","EUR"),
            CurrencyPair.of("BAT","USD"),
            CurrencyPair.of("COMP","ETH"),
            CurrencyPair.of("COMP","EUR"),
            CurrencyPair.of("COMP","USD"),
            CurrencyPair.of("GBP","USD"),
            CurrencyPair.of("TRX","ETH"),
            CurrencyPair.of("TRX","EUR"),
            CurrencyPair.of("TRX","USD"),
            CurrencyPair.of("SC","ETH"),
            CurrencyPair.of("SC","EUR"),
            CurrencyPair.of("SC","USD"),
            CurrencyPair.of("ATOM","ETH"),
            CurrencyPair.of("ATOM","EUR"),
            CurrencyPair.of("ATOM","USD"),
            CurrencyPair.of("LSK","ETH"),
            CurrencyPair.of("LSK","EUR"),
            CurrencyPair.of("LSK","USD"),
            CurrencyPair.of("PAXG","ETH"),
            CurrencyPair.of("PAXG","EUR"),
            CurrencyPair.of("PAXG","USD"),
            CurrencyPair.of("EUR","CAD"),
            CurrencyPair.of("EUR","JPY"),
            CurrencyPair.of("EUR","GBP"),
            CurrencyPair.of("EUR","CHF"),
            CurrencyPair.of("EUR","USD"),
            CurrencyPair.of("EUR","AUD"),
            CurrencyPair.of("USD","CAD"),
            CurrencyPair.of("USD","JPY"),
            CurrencyPair.of("USD","CHF"),
            CurrencyPair.of("GNO","ETH"),
            CurrencyPair.of("GNO","EUR"),
            CurrencyPair.of("GNO","USD"),
            CurrencyPair.of("LINK","ETH"),
            CurrencyPair.of("LINK","EUR"),
            CurrencyPair.of("LINK","USD"),
            CurrencyPair.of("ALGO","ETH"),
            CurrencyPair.of("ALGO","EUR"),
            CurrencyPair.of("ALGO","USD"),
            CurrencyPair.of("BCH","ETH"),
            CurrencyPair.of("BCH","GBP"),
            CurrencyPair.of("BCH","EUR"),
            CurrencyPair.of("BCH","USD"),
            CurrencyPair.of("BCH","AUD"),
            CurrencyPair.of("NANO","ETH"),
            CurrencyPair.of("NANO","EUR"),
            CurrencyPair.of("NANO","USD"),
            CurrencyPair.of("QTUM","ETH"),
            CurrencyPair.of("QTUM","EUR"),
            CurrencyPair.of("QTUM","USD"),
            CurrencyPair.of("WAVES","ETH"),
            CurrencyPair.of("WAVES","EUR"),
            CurrencyPair.of("WAVES","USD"),
            CurrencyPair.of("LTC","ETH"),
            CurrencyPair.of("LTC","GBP"),
            CurrencyPair.of("LTC","EUR"),
            CurrencyPair.of("LTC","USD"),
            CurrencyPair.of("LTC","AUD"),
            CurrencyPair.of("ETC","ETH"),
            CurrencyPair.of("ETC","EUR"),
            CurrencyPair.of("ETC","USD"),
            CurrencyPair.of("AUD","JPY"),
            CurrencyPair.of("AUD","USD"),
            CurrencyPair.of("STORJ","ETH"),
            CurrencyPair.of("STORJ","EUR"),
            CurrencyPair.of("STORJ","USD"),
            CurrencyPair.of("KNC","ETH"),
            CurrencyPair.of("KNC","EUR"),
            CurrencyPair.of("KNC","USD")
    );
}
